import { ArrowUpRight, Bot, Clock3, Cpu } from "lucide-react";
import { memo } from "react";

const severityClass = { HIGH: "text-rose-400 bg-rose-500/10 border-rose-500/25", MEDIUM: "text-amber-400 bg-amber-500/10 border-amber-500/25", LOW: "text-emerald-400 bg-emerald-500/10 border-emerald-500/25" };

function AIRecommendationCard({ recommendation, source, onClick }) {
  if (!recommendation || typeof recommendation !== "object") return null;

  const severity = recommendation.severity ?? "LOW";
  const category = recommendation.category ?? "";
  const partNo = recommendation.partNo ?? recommendation.partNumber ?? "";
  const title = recommendation.title ?? "";
  const reasoning = recommendation.reasoning ?? "";
  const tags = Array.isArray(recommendation.tags) ? recommendation.tags : [];
  const confidence =
    typeof recommendation.confidence === "number" ? recommendation.confidence : Number(recommendation.confidence ?? 0);

  const time = recommendation.timestamp
    ? new Date(recommendation.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })
    : "";

  return (
    <button
      onClick={onClick}
      className="w-full text-left theme-bg-card border theme-border rounded-2xl p-5 hover:theme-card-hover hover:-translate-y-0.5 transition-all duration-300 group"
    >
      <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-3 mb-4">
        <div className="flex flex-wrap gap-2">
          <span
            className={`text-[10px] border rounded-md px-2 py-1 font-bold tracking-widest ${
              severityClass[severity] ?? severityClass.LOW
            }`}
          >
            {severity} PRIORITY
          </span>
          <span className="text-[10px] theme-cyan-bg theme-cyan-border theme-cyan border rounded-md px-2 py-1 font-bold tracking-widest">
            {category}
          </span>
        </div>
        <span className="flex items-center gap-1.5 text-[10px] theme-muted">
          <Clock3 size={11} />
          {time}
        </span>
      </div>

      <div className="flex justify-between gap-4">
        <div>
          <p className="text-[10px] theme-muted uppercase tracking-widest mb-1">Part {partNo}</p>
          <h3 className="theme-text font-semibold group-hover:theme-cyan transition-colors">{title}</h3>
          <p className="text-sm theme-muted leading-relaxed mt-2">{reasoning}</p>
        </div>
        <ArrowUpRight size={18} className="theme-muted group-hover:theme-cyan shrink-0" />
      </div>

      <div className="flex flex-wrap items-end justify-between gap-3 mt-5 pt-4 border-t theme-border">
        <div className="flex flex-wrap gap-1.5">
          {tags.map((tag, i) => (
            <span
              key={`${tag ?? "tag"}-${i}`}
              className="text-[9px] theme-bg-card-soft border theme-border theme-muted rounded px-2 py-1 tracking-wider"
            >
              {tag}
            </span>
          ))}
        </div>
        <div className="text-right">
          <p className="text-[10px] theme-text font-semibold">{confidence}% CONFIDENCE</p>
          <p className="text-[9px] theme-muted flex items-center gap-1 mt-1">
            {source === "gemini" ? <Bot size={10} /> : <Cpu size={10} />}
            Generated by {source === "gemini" ? "Gemini AI" : "Fallback Intelligence Engine"}
          </p>
        </div>
      </div>
    </button>
  );
}

export default memo(AIRecommendationCard);
